#services:
#  mongodb:
#    image: 'mongo:latest'
#    container_name: datastore-mongodb-1
#    environment:
#      - 'MONGO_INITDB_DATABASE=mydatabase'
#      - 'MONGO_INITDB_ROOT_PASSWORD=secret'
#      - 'MONGO_INITDB_ROOT_USERNAME=root'
#    ports:
#      - '27018:27017'
